### ISSUE TITLE
Multi-allelic sites for somatic mode (somdict() method)

### ISSUE THREAD

**Issue by kamyshova** [AstraZeneca-NGS/VarDictJava#68]
We've found out that multi-allelic sites are not called when running the paired variant calling; VarDict takes first allelled variation (like it does in amplicon mode as stated in [#65 issue](https://github.com/AstraZeneca-NGS/VarDictJava/issues/65)).
This logic is implemented in the following code lines:
 https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/VarDict.java#L485,
https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/VarDict.java#L517
https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/VarDict.java#L773
@mjafin, should we update the somatic postprocessing mode in somdict() method?

**Comment by mjafin** [comment]
Yes please

**Comment by kamyshova** [comment]
@mjafin we did this update, could we ask you about sample data to test it?

**Comment by mjafin** [comment]
I don't think I have any test data. Do you have any cases you can demonstrate? If it works for you I'm happy too. @chapmanb can maybe run the Dream challenge data set after all the current fixes are in to see what happens to our sensitivity and PPV

**Comment by kamyshova** [comment]
@mjafin we've fixed logic in code lines mentioned above plus one more:
https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/VarDict.java#L703
We`ve replaced analysis of one first variant by analysis of all variants found in the specified position (making a loop through the array of good variants).
The fix produces the following [results](https://github.com/AstraZeneca-NGS/VarDictJava/files/878901/result.tar.gz) for the given test [data](https://github.com/AstraZeneca-NGS/VarDictJava/files/878902/data.tar.gz).
As we understand, the fixed version provides the expected output, i.e. 4 additional (allelic) variations at 4 positions (each additional variation is caused by changing one of 4 code lines mentioned above).

**Comment by mjafin** [comment]
Thanks @kamyshova, nice work.

**Comment by mjafin** [comment]
Does this fix also https://github.com/AstraZeneca-NGS/VarDictJava/issues/65 (amplicon mode issue at the end of the thread)?

**Comment by kamyshova** [comment]
@mjafin the fix for #65 is in separate branch https://github.com/AstraZeneca-NGS/VarDictJava/tree/f_amp_multi-allelic and results are present in issue's conversation.
Fixes for this issue are in branch https://github.com/AstraZeneca-NGS/VarDictJava/tree/f_multi_allelic_somdict

**Comment by mjafin** [comment]
Shall we get these fixes in a release and have the related folks test it on their sides?

**Comment by kamyshova** [comment]
@mjafin we are ready to do this once @tfenne rebases his pull request

**Comment by kamyshova** [comment]
@mjafin we've done a new [release v1.5.0](https://github.com/AstraZeneca-NGS/VarDictJava/releases/tag/v1.5.0) which includes the multi-allelic site fixes https://github.com/AstraZeneca-NGS/VarDictJava/issues/68 , https://github.com/AstraZeneca-NGS/VarDictJava/issues/65 and [PR#50](https://github.com/AstraZeneca-NGS/VarDictJava/pull/50).

**Comment by mjafin** [comment]
@kamyshova beautiful!

@tfenne @bramslabbinck can you check on your respective sides if the issues with VarDictJava are now addressed satisfactorily?

**Comment by jamie-a** [comment]
@mjafin Hi there, I've just tested the multiallelic calling in amplicon aware mode and it seems to still not be picking them up. I'm looking at a previously validated multiallelic position that has clear evidence in the bam and it's not being called. Worryingly it also seems to not get called when I revert to a 3 column bed file and remove the -a option. It is being called by Unified Genotyper, and as I say, has been validated separately.

Happy to upload the slice of bed/bam with the variant if required?

**Comment by mjafin** [comment]
Please do

**Comment by jamie-a** [comment]
Sure.

Variant is at 11_108114461
[test.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/893403/test.tar.gz)

**Comment by kamyshova** [comment]
Hi @mjafin and @jamie-a 
Thank you!
We`ll check it.

**Comment by kamyshova** [comment]
Hi @jamie-a 
As we understand you expect a variant at 11_108114461 in the file (test.bed) you've provided.
We found out that this region `doesn't contain` the 11_108114461 position; here is the region for the Chromosome 11:
chr11	108114569	108114839	ATM	0	.	108114595	108114816

VarDict has detected variations in several positions at Chromosome 11, but all of them have been filtered out by isGoodVar() method that checks whether a variant meets specified criteria.
Varations have been detected in the following positions:
| Position	        | Number of variations	| Position is in a keySet	| isGoodVars |
| 108114661	| 4	                                |                   +	                |                -   |
| 108114662	| 4	                                |                   +	                |                -   |
| 108114677	| 3	                                |                   +	                |                -   |
| 108114684	| 1	                                |                   +	                |                -   |
| 108114687	| 2	                                |                   +	                |                -   |
| 108114689	| 1	                                |                   +	                |                -   |
| 108114839	| 3                                    |	            -	                |    not known|

**Comment by jamie-a** [comment]
Thanks @kamyshova , my mistake, an amplicon was dropped from the bed file, not sure how I missed that!

**Comment by kamyshova** [comment]
@jamie-a mainly, the variants are filtered in this method: 
https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/src/main/java/com/astrazeneca/vardict/VarDict.java#L5975
For example, a variant appears in the output if:
- variant frequency is more than 25% or reference allele does not have much better mapping quality than the variant;
OR
- the ratio of high-quality reads to low-quality reads is larger than the threshold specified by -o option (default=1.5).

**Comment by PolinaBevad** [comment]
@mjafin, @kamyshova, @jamie-a, hello!
I will close this issue because everything discussed was implemented.
Thanks to all!
